# Generated by Django 5.0 on 2024-05-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notes", "0002_alter_notes_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="drop_down",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WIN10", "Windows 10"),
                    ("WIN11", "Windows 11"),
                    ("WIN8", "Windows 8"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
