# Generated by Django 5.0 on 2024-05-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notes", "0004_dropdown_alter_notes_drop_down"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dropdown",
            name="drop_down",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="notes",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
